# Generated by Django 3.2.5 on 2021-07-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
