# Generated by Django 3.2.5 on 2021-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('Poster', models.ImageField(upload_to='')),
                ('Date', models.DateField()),
                ('Content', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
