# Generated by Django 3.2.5 on 2021-07-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='announcements',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='announcements',
            old_name='Poster',
            new_name='poster',
        ),
    ]
